version: '3'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 3G
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
    volumes:
      # - ./strapi:/opt/app
      - /opt/app/node_modules
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - strapi-network

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: zhi_zhao_tech_strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2wsx
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - strapi
    networks:
      - strapi-network

volumes:
  postgres-data:

networks:
  strapi-network:
    name: strapi-network
    driver: bridge