version: '3'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 3G
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
    volumes:
      - node_modules:/opt/app/node_modules  # 給 node_modules volume 一個固定名稱
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - strapi-network

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: zhi_zhao_tech_strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2wsx
    # volumes: 定義了容器的持久化存儲，這裡將名為 postgres-data 的卷掛載到 PostgreSQL 的數據目錄 /var/lib/postgresql/data，確保數據在容器重啟或刪除後仍然存在。
    # 在這裡，A 是 postgres-data（Docker 端的卷），B 是 /var/lib/postgresql/data（容器內的路徑）。
    # A 是 Docker 端的映射檔案，因為它是定義在 Docker 卷中的數據存儲。
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - strapi
    networks:
      - strapi-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres-data:
  node_modules:    # 在這裡定義 node_modules volume

networks:
  strapi-network:
    name: strapi-network
    driver: bridge